# RustGame3 GUI Configuration
# This file controls the starting settings for the visual demo
# All settings can be changed at runtime using keyboard shortcuts

[grid]
# Grid dimensions (number of cells)
# Default: 40x40
cols = 80
rows = 80

# Cell size in pixels
# Default: 20.0 width, 15.0 height
cell_width = 20.0
cell_height = 15.0

[observer]
# Starting observer position (grid coordinates)
# Must be within grid bounds: 0 <= x < cols, 0 <= y < rows
# Default: center of grid (20, 20 for 40x40 grid)
x = 20
y = 20

# Messy position state
# messy_x: true = observer occupies 2 horizontal cells (x, x+1)
# messy_y: true = observer occupies 2 vertical cells (y, y+1)
# Possible values: true, false
# Default: both false
messy_x = false
messy_y = false

[subcell]
# Sub-cell display mode
# Controls BOTH the visual grid overlay AND the navigation grid size
# Possible values:
#   "none"  - No sub-cell grid displayed (navigation uses 3x3 by default)
#   "1x1"   - Show 1x1 sub-cell grid (cell == sub-cell) + 1x1 navigation
#   "2x2"   - Show 2x2 sub-cell grid (4 sub-cells per cell) + 2x2 navigation
#   "3x3"   - Show 3x3 sub-cell grid (9 sub-cells per cell) + 3x3 navigation
# Default: "none"
# Toggle at runtime: G key (cycles None → 1x1 → 2x2 → 3x3 → None)
display_mode = "2x2"

# Sub-cell movement system
# When enabled, actors use fine-grained sub-cell pathfinding with collision avoidance
# Possible values: true, false
# Default: false
# Toggle at runtime: S key
movement_enabled = true

# Show sub-cell debug markers
# Green circles = current sub-cell, Yellow circles = reserved sub-cell
# Possible values: true, false
# Default: false (hidden for cleaner view)
# Toggle at runtime: B key
show_markers = false

# Default reservation mode for sub-cell collision avoidance
# Possible values:
#   "Square"           - Reserve 2×2 square in movement direction (max spacing)
#   "Diagonal"         - Diagonal moves require H/V anchor reservation
#   "NoDiagonal"       - Diagonal moves not allowed (grid-aligned only)
#   "AntiCross"        - Prevent counter-diagonal crossing patterns
#   "Basic3"           - Limit to 3 candidates (best + ±45°), enforce monotonic distance decrease
#   "Basic3AntiCross"  - Basic3 + anti-cross checking (most restrictive)
# Default: "Square"
# Toggle at runtime: Q key (cycles through all modes)
reservation_mode = "DestinationDirect"

# Early reservation system
# When enabled, actors reserve their next sub-cell immediately upon reaching current sub-cell
# instead of waiting to center on current position first
# Possible values: true, false
# Default: false
# Toggle at runtime: E key
early_reservation_enabled = true

# Sub-cell offset alignment
# Offsets the sub-cell grid alignment for all actors
# Possible values:
#   "None" - No offset, standard grid alignment (default)
#   "X"    - Offset by 0.5 sub-cells horizontally
#   "Y"    - Offset by 0.5 sub-cells vertically
#   "XY"   - Offset by 0.5 sub-cells in both directions
# Default: "None"
# Toggle at runtime: T key (cycles None → X → Y → XY → None)
offset = "XY"

[actors]
# Default actor speed in pixels per second
# Higher = faster movement
# Default: 120.0
default_speed = 50.0

# Actor size as percentage of cell size
# Value between 0.0 and 1.0
# Default: 0.9 (90% of smallest cell dimension)
size_ratio = 0.9

# Collision radius as percentage of cell size
# Value between 0.0 and 1.0
# Default: 0.3 (30% of smallest cell dimension)
collision_radius_ratio = 0.3

[visual]
# Window title
# Default: "RustGame3 - Grid Raycasting Demo"
window_title = "RustGame3 - Grid Raycasting Demo"

# Background color (RGB values 0-255)
# Default: dark gray (30, 30, 30)
background_r = 30
background_g = 30
background_b = 30

# Show corner indicators
# White squares = interesting corners, Yellow squares = non-interesting corners
# Possible values: true, false
# Default: true
show_corners = true

[default_grid_file]
# Path to default grid layout file
# If file exists, it will be loaded on startup
# Format: same as copy/paste (■ for blocked, s for observer, etc.)
# Set to empty string "" to start with empty grid
# Default: "claude_tasks/default_grid_layout.txt"
path = "claude_tasks/default_grid_layout.txt"

[logging]
# Enable action logging to JSON file
# Logs all actions (spawn actor, set destination, etc.)
# Possible values: true, false
# Default: true
enable_action_log = true

# Action log file path
# Default: "action_log.json"
action_log_path = "action_log.json"
